### ISSUE TITLE
[Pathway Content Issue]: Glycosaminoglycan identifiers in WP5395

### ISSUE THREAD

**Issue by danidi** [wikipathways/wikipathways-help#45]
### What is the issue with the pathway?

[WP5395](https://classic.wikipathways.org/index.php/Pathway:WP5395) contains glycosaminoglycans with identifiers from MetaNetX in the comments (e.g. https://www.metanetx.org/chem_info/MNXM18007). 
Two questions here: 
1.) can we use this type of identifier directly as identifier rather than a comment (not supported in PathVisio).
2.) should those data nodes be metabolites or proteins? From the name/ID it looks like the metabolite is connected to a protein.

### What kind of content issue is this?

Other

### Should this pathway be deleted?

- [ ] Pathway should be deleted

**Comment by khanspers** [comment]
1. Since the MetaNetX identifier is not supported in BridgeDb, they can't be used directly as identifiers effectively. 
2. After some discussions during the Curator's meeting, it makes the most sense to have the nodes as metabolites, as they currently are, but representing only the modification (glycosaminoglycan) part and not the protein. The protein could be represented as a generic "protein" label (could be a rectangle to resemble a node) that is grouped with each metabolite if showing the generic protein is important. 

Here's an example of another pathway which similarly has glycans represented as metabolites (without the protein or amino acid), using KEGG glycan identifiers: 
https://www.wikipathways.org/pathways/WP5153.html
